from typing import Any, Optional, TypeVar

Logger = TypeVar('Logger')

class Xlsx:
    def __init__(self, author: Optional[str] = ..., comments: Optional[str] = ..., logger: Optional[Logger] = ...) -> None: ...
    def save_collection(self, collection: dict[str, Any], to_file: str) -> None: ...
    def save_wantlist(self, wantlist: dict[str, Any], to_file: str) -> None: ...
