from . import __project__ as __project__
from typing import Optional
from .logger import Logger


class Discogs:
    API_BASEURL: str = ...
    API_FORMAT: str = ...
    API_LIMIT: int = ...
    API_RATELIMIT_STATUS: int = ...
    API_RATELIMIT_TIME: int = ...

    def __init__(self,
                 key: str,
                 currency: str = ...,
                 logger: Optional[Logger] = ...) -> None: ...

    def get_collection(self, details: bool = ..., prices: bool = ...): ...
    def get_wantlist(self, details: bool = ..., prices: bool = ...): ...
