from argparse import Action, ArgumentParser, Namespace
from typing import Any, Optional

class _WantlistAction(Action):
    def __call__(self, parser: ArgumentParser, namespace: Namespace, values: list[str], option_string: Optional[str]=...) -> None: ...

class Options:
    def __init__(self) -> None: ...
    def __setattr__(self, name: Any, value: Any) -> None: ...
    @property
    def all(self) -> dict[str, Any]: ...
