import argparse
from . import __project__ as __project__
from typing import Any, Optional


class _WantlistAction(argparse.Action):
    def __init__(
        self,
        option_strings: Any,
        dest: Any,
        default: bool = ...,
        required: bool = ...,
        help: Optional[Any] = ...,
        metavar: Optional[Any] = ...) -> None: ...
    def __call__(self, parser: Any, namespace: Any, values: Any,
                 option_string: Optional[Any] = ...) -> None: ...


class Options:
    def __init__(self) -> None: ...
    @property
    def apikey(self) -> str: ...
    @property
    def currency(self) -> str: ...
    @property
    def debug(self) -> bool: ...
    @property
    def details(self) -> bool: ...
    @property
    def file(self) -> str: ...
    @property
    def options(self) -> dict[str, Any]: ...
    @property
    def prices(self) -> bool: ...
    @property
    def quiet(self) -> bool: ...
    @property
    def wantlist(self) -> bool: ...
